package ge.itvet.olympic;

public enum Country {
    AFGHANISTAN, THE_GAMBIA, NORTH_MACEDONIA, ALBANIA, GEORGIA, NORWAY, ALGERIA, GERMANY, OMAN,
    AMERICAN_SAMOA, GHANA, PAKISTAN, ANDORRA, GREECE, PALAU, ANGOLA, GRENADA, PALESTINE,
    ANTIGUA_AND_BARBUDA, GUAM, PANAMA, ARGENTINA, GUATEMALA, PAPUA_NEW_GUINEA, ARMENIA, GUINEA,
    PARAGUAY, ARUBA, GUINEA_BISSAU, PERU, AUSTRALIA, GUYANA, PHILIPPINES, AUSTRIA, HAITI, POLAND, AZERBAIJAN,
    HONDURAS, PORTUGAL, THE_BAHAMAS, HONG_KONG, PUERTO_RICO, BAHRAIN, HUNGARY, QATAR, BANGLADESH,
    ICELAND, ROMANIA, BARBADOS, INDIA, RUSSIAN_FEDERATION, BELARUS, INDONESIA, RWANDA, BELGIUM, IRAN,
    SAINT_KITTS_AND_NEVIS, BELIZE, IRAQ, SAINT_LUCIA, BENIN, IRELAND, SAINT_VINCENT_AND_THE_GRENADINES,
    BERMUDA, ISRAEL, SAMOA, BHUTAN, ITALY, SAN_MARINO, BOLIVIA, JAMAICA, SAO_TOME_AND_PRINCIPE,
    BOSNIA_AND_HERZEGOVINA, JAPAN, SAUDI_ARABIA, BOTSWANA, JORDAN, SENEGAL, BRAZIL, KAZAKHSTAN, SERBIA,
    BRITISH_VIRGIN_ISLANDS, KENYA, SEYCHELLES, BRUNEI_DARUSSALAM, KIRIBATI, SIERRA_LEONE, BULGARIA, KOREA_NORTH,
    SINGAPORE, BURKINA_FASO, KOREA_SOUTH, SLOVAKIA, BURUNDI, KOSOVO, SLOVENIA, CAMBODIA, KUWAIT,
    SOLOMON_ISLANDS, CAMEROON, KYRGYZSTAN, SOMALIA, CANADA, LAOS, SOUTH_AFRICA, CAPE_VERDE, LATVIA,
    SOUTH_SUDAN, CAYMAN_ISLANDS, LEBANON, SPAIN, CENTRAL_AFRICAN_REPUBLIC, LESOTHO, SRI_LANKA, CHAD, LIBERIA,
    SUDAN, CHILE, LIBYA, SURINAME, CHINA, LIECHTENSTEIN, SWEDEN, COLOMBIA, LITHUANIA, SWITZERLAND, COMOROS,
    LUXEMBOURG, SYRIA, CONGO, MADAGASCAR, TAIWAN_CHINESE_TAIPEI, MALAWI, TAJIKISTAN,
    REPUBLIC_OF_THE_COOK_ISLANDS, MALAYSIA, TANZANIA, COSTA_RICA, MALDIVES, THAILAND, COTE_D_IVOIRE, MALI,
    TOGO, CROATIA, MALTA, TONGA, CUBA, MARSHALL_ISLANDS, TRINIDAD_AND_TOBAGO, CYPRUS, MAURITANIA, TUNISIA,
    CZECH_REPUBLIC, MAURITIUS, TURKEY, DENMARK, MEXICO, TURKMENISTAN, DJIBOUTI, FED_STATES_OF_MICRONESIA,
    TUVALU, DOMINICA, MOLDOVA, UGANDA, DOMINICAN_REPUBLIC, MONACO, UKRAINE, EAST_TIMOR_TIMOR_LESTE,
    MONGOLIA, UNITED_ARAB_EMIRATES, ECUADOR, MONTENEGRO, UNITED_KINGDOM_GREAT_BRITAIN, EGYPT, MOROCCO,
    UNITED_STATES, EL_SALVADOR, MOZAMBIQUE, URUGUAY, EQUATORIAL_GUINEA, MYANMAR_BURMA, UZBEKISTAN,
    ERITREA, NAMIBIA, VANUATU, ESTONIA, NAURU, VENEZUELA, ESWATINI, NEPAL, VIETNAM, ETHIOPIA, NETHERLANDS,
    VIRGIN_ISLANDS_US, FIJI, NEW_ZEALAND, YEMEN, FINLAND, NICARAGUA, ZAMBIA, FRANCE, NIGER, ZIMBABWE, GABON,
    NIGERIA;

}
